/* eslint-disable sort-keys */
import Locations from './locations';

type PredefinedTileImage = {
  id: string;
  name: string;
  imageSource: string;
  top: Locations;
  left: Locations;
  middle: Locations[];
  right: Locations;
  bottom: Locations;
  isSpecial: boolean;
};

export const PREDEFINED_TILE_IMAGES: PredefinedTileImage[] = [
  {
    id: '001',
    name: 'Road_1',
    imageSource: './Elements/Tiles/Roads/Road_1.png',
    top: Locations.FIELD,
    left: Locations.ROAD,
    middle: [Locations.ROAD],
    right: Locations.ROAD,
    bottom: Locations.FIELD,
    isSpecial: false,
  },
  {
    id: '002',
    name: 'Road_2',
    imageSource: './Elements/Tiles/Roads/Road_2.png',
    top: Locations.FIELD,
    left: Locations.FIELD,
    middle: [Locations.ROAD],
    right: Locations.ROAD,
    bottom: Locations.ROAD,
    isSpecial: false,
  },
  {
    id: '003',
    name: 'Road_3',
    imageSource: './Elements/Tiles/Roads/Road_3.png',
    top: Locations.FIELD,
    left: Locations.FIELD,
    middle: [Locations.MONASTERY],
    right: Locations.FIELD,
    bottom: Locations.ROAD,
    isSpecial: false,
  },
  {
    id: '004',
    name: 'Road_4',
    imageSource: './Elements/Tiles/Roads/Road_4.png',
    top: Locations.ROAD,
    left: Locations.ROAD,
    middle: [Locations.TAVERN],
    right: Locations.ROAD,
    bottom: Locations.ROAD,
    isSpecial: false,
  },
  {
    id: '005',
    name: 'City_1',
    imageSource: './Elements/Tiles/City/City_1.png',
    top: Locations.CITY,
    left: Locations.ROAD,
    middle: [Locations.ROAD],
    right: Locations.ROAD,
    bottom: Locations.FIELD,
    isSpecial: false,
  },
  {
    id: '006',
    name: 'City_2',
    imageSource: './Elements/Tiles/City/City_2.png',
    top: Locations.CITY,
    left: Locations.ROAD,
    middle: [Locations.ROAD],
    right: Locations.FIELD,
    bottom: Locations.ROAD,
    isSpecial: false,
  },
  {
    id: '007',
    name: 'City_3',
    imageSource: './Elements/Tiles/City/City_3.png',
    top: Locations.CITY,
    left: Locations.FIELD,
    middle: [Locations.ROAD],
    right: Locations.ROAD,
    bottom: Locations.ROAD,
    isSpecial: false,
  },
  {
    id: '008',
    name: 'City_4',
    imageSource: './Elements/Tiles/City/City_4.png',
    top: Locations.CITY,
    left: Locations.ROAD,
    middle: [Locations.TAVERN],
    right: Locations.ROAD,
    bottom: Locations.ROAD,
    isSpecial: false,
  },
  {
    id: '009',
    name: 'City_5',
    imageSource: './Elements/Tiles/City/City_5.png',
    top: Locations.CITY,
    left: Locations.FIELD,
    middle: [Locations.FIELD],
    right: Locations.FIELD,
    bottom: Locations.FIELD,
    isSpecial: false,
  },
  {
    id: '010',
    name: 'City_6',
    imageSource: './Elements/Tiles/City/City_6.png',
    top: Locations.CITY,
    left: Locations.CITY,
    middle: [Locations.CITY],
    right: Locations.CITY,
    bottom: Locations.FIELD,
    isSpecial: false,
  },
  {
    id: '011',
    name: 'City_7',
    imageSource: './Elements/Tiles/City/City_7.png',
    top: Locations.CITY,
    left: Locations.CITY,
    middle: [Locations.CITY],
    right: Locations.CITY,
    bottom: Locations.FIELD,
    isSpecial: true,
  },
  {
    id: '012',
    name: 'City_8',
    imageSource: './Elements/Tiles/City/City_8.png',
    top: Locations.CITY,
    left: Locations.CITY,
    middle: [Locations.CITY],
    right: Locations.CITY,
    bottom: Locations.ROAD,
    isSpecial: false,
  },
  {
    id: '013',
    name: 'City_9',
    imageSource: './Elements/Tiles/City/City_9.png',
    top: Locations.CITY,
    left: Locations.CITY,
    middle: [Locations.CITY],
    right: Locations.CITY,
    bottom: Locations.ROAD,
    isSpecial: true,
  },
  {
    id: '014',
    name: 'City_10',
    imageSource: './Elements/Tiles/City/City_10.png',
    top: Locations.CITY,
    left: Locations.CITY,
    middle: [Locations.CITY],
    right: Locations.CITY,
    bottom: Locations.CITY,
    isSpecial: true,
  },
  {
    id: '015',
    name: 'Joiner_1',
    imageSource: './Elements/Tiles/Joiners/Joiner_1.png',
    top: Locations.CITY,
    left: Locations.CITY,
    middle: [Locations.CITY],
    right: Locations.FIELD,
    bottom: Locations.FIELD,
    isSpecial: false,
  },
  {
    id: '016',
    name: 'Joiner_2',
    imageSource: './Elements/Tiles/Joiners/Joiner_2.png',
    top: Locations.CITY,
    left: Locations.CITY,
    middle: [Locations.CITY],
    right: Locations.FIELD,
    bottom: Locations.FIELD,
    isSpecial: true,
  },
  {
    id: '017',
    name: 'Joiner_3',
    imageSource: './Elements/Tiles/Joiners/Joiner_3.png',
    top: Locations.FIELD,
    left: Locations.ROAD,
    middle: [Locations.ROAD],
    right: Locations.ROAD,
    bottom: Locations.FIELD,
    isSpecial: false,
  },
  {
    id: '018',
    name: 'Joiner_4',
    imageSource: './Elements/Tiles/Joiners/Joiner_4.png',
    top: Locations.FIELD,
    left: Locations.CITY,
    middle: [Locations.CITY],
    right: Locations.CITY,
    bottom: Locations.FIELD,
    isSpecial: true,
  },
  {
    id: '019',
    name: 'Joiner_5',
    imageSource: './Elements/Tiles/Joiners/Joiner_5.png',
    top: Locations.CITY,
    left: Locations.CITY,
    middle: [Locations.CITY, Locations.ROAD],
    right: Locations.ROAD,
    bottom: Locations.ROAD,
    isSpecial: false,
  },
  {
    id: '020',
    name: 'Joiner_6',
    imageSource: './Elements/Tiles/Joiners/Joiner_6.png',
    top: Locations.CITY,
    left: Locations.CITY,
    middle: [Locations.CITY, Locations.ROAD],
    right: Locations.ROAD,
    bottom: Locations.ROAD,
    isSpecial: true,
  },
  {
    id: '021',
    name: 'Monastery',
    imageSource: './Elements/Tiles/Monastery/Monastery_1.png',
    top: Locations.FIELD,
    left: Locations.FIELD,
    middle: [Locations.MONASTERY],
    right: Locations.FIELD,
    bottom: Locations.ROAD,
    isSpecial: true,
  },
  {
    id: '022',
    name: 'Garden',
    imageSource: './Elements/Tiles/Monastery/Monastery_2.png',
    top: Locations.GARDEN,
    left: Locations.GARDEN,
    middle: [Locations.GARDEN],
    right: Locations.GARDEN,
    bottom: Locations.GARDEN,
    isSpecial: true,
  },
  {
    id: '023',
    name: 'Splitter_1',
    imageSource: './Elements/Tiles/Splitters/Splitter_1.png',
    top: Locations.CITY,
    left: Locations.FIELD,
    middle: [Locations.FIELD],
    right: Locations.FIELD,
    bottom: Locations.CITY,
    isSpecial: false,
  },
  {
    id: '024',
    name: 'Splitter_2',
    imageSource: './Elements/Tiles/Splitters/Splitter_2.png',
    top: Locations.CITY,
    left: Locations.CITY,
    middle: [Locations.FIELD],
    right: Locations.FIELD,
    bottom: Locations.FIELD,
    isSpecial: false,
  },
];
