import Locations from './locations';

export const tilesData = [
  {
    id: '001_1',
    edges: {
      top: Locations.FIELD,
      right: Locations.ROAD,
      bottom: Locations.FIELD,
      left: Locations.ROAD,
    },
    middle: [Locations.ROAD],
    isSpecial: false,
  },
  {
    id: '001_2',
    edges: {
      top: Locations.FIELD,
      right: Locations.ROAD,
      bottom: Locations.FIELD,
      left: Locations.ROAD,
    },
    middle: [Locations.ROAD],
    isSpecial: false,
  },
  {
    id: '001_3',
    edges: {
      top: Locations.FIELD,
      right: Locations.ROAD,
      bottom: Locations.FIELD,
      left: Locations.ROAD,
    },
    middle: [Locations.ROAD],
    isSpecial: false,
  },
  {
    id: '001_4',
    edges: {
      top: Locations.FIELD,
      right: Locations.ROAD,
      bottom: Locations.FIELD,
      left: Locations.ROAD,
    },
    middle: [Locations.ROAD],
    isSpecial: false,
  },
  {
    id: '001_5',
    edges: {
      top: Locations.FIELD,
      right: Locations.ROAD,
      bottom: Locations.FIELD,
      left: Locations.ROAD,
    },
    middle: [Locations.ROAD],
    isSpecial: false,
  },
  {
    id: '001_6',
    edges: {
      top: Locations.FIELD,
      right: Locations.ROAD,
      bottom: Locations.FIELD,
      left: Locations.ROAD,
    },
    middle: [Locations.ROAD],
    isSpecial: false,
  },
  {
    id: '001_7',
    edges: {
      top: Locations.FIELD,
      right: Locations.ROAD,
      bottom: Locations.FIELD,
      left: Locations.ROAD,
    },
    middle: [Locations.ROAD],
    isSpecial: false,
  },
  {
    id: '001_8',
    edges: {
      top: Locations.FIELD,
      right: Locations.ROAD,
      bottom: Locations.FIELD,
      left: Locations.ROAD,
    },
    middle: [Locations.ROAD],
    isSpecial: false,
  },
  {
    id: '002_1',
    edges: {
      top: Locations.FIELD,
      right: Locations.ROAD,
      bottom: Locations.ROAD,
      left: Locations.FIELD,
    },
    middle: [Locations.ROAD],
    isSpecial: false,
  },
  {
    id: '002_2',
    edges: {
      top: Locations.FIELD,
      right: Locations.ROAD,
      bottom: Locations.ROAD,
      left: Locations.FIELD,
    },
    middle: [Locations.ROAD],
    isSpecial: false,
  },
  {
    id: '002_3',
    edges: {
      top: Locations.FIELD,
      right: Locations.ROAD,
      bottom: Locations.ROAD,
      left: Locations.FIELD,
    },
    middle: [Locations.ROAD],
    isSpecial: false,
  },
  {
    id: '002_4',
    edges: {
      top: Locations.FIELD,
      right: Locations.ROAD,
      bottom: Locations.ROAD,
      left: Locations.FIELD,
    },
    middle: [Locations.ROAD],
    isSpecial: false,
  },
  {
    id: '002_5',
    edges: {
      top: Locations.FIELD,
      right: Locations.ROAD,
      bottom: Locations.ROAD,
      left: Locations.FIELD,
    },
    middle: [Locations.ROAD],
    isSpecial: false,
  },
  {
    id: '002_6',
    edges: {
      top: Locations.FIELD,
      right: Locations.ROAD,
      bottom: Locations.ROAD,
      left: Locations.FIELD,
    },
    middle: [Locations.ROAD],
    isSpecial: false,
  },
  {
    id: '002_7',
    edges: {
      top: Locations.FIELD,
      right: Locations.ROAD,
      bottom: Locations.ROAD,
      left: Locations.FIELD,
    },
    middle: [Locations.ROAD],
    isSpecial: false,
  },
  {
    id: '002_8',
    edges: {
      top: Locations.FIELD,
      right: Locations.ROAD,
      bottom: Locations.ROAD,
      left: Locations.FIELD,
    },
    middle: [Locations.ROAD],
    isSpecial: false,
  },
  {
    id: '002_9',
    edges: {
      top: Locations.FIELD,
      right: Locations.ROAD,
      bottom: Locations.ROAD,
      left: Locations.FIELD,
    },
    middle: [Locations.ROAD],
    isSpecial: false,
  },
  {
    id: '003_1',
    edges: {
      top: Locations.FIELD,
      right: Locations.ROAD,
      bottom: Locations.ROAD,
      left: Locations.ROAD,
    },
    middle: [Locations.TAVERN],
    isSpecial: false,
  },
  {
    id: '003_2',
    edges: {
      top: Locations.FIELD,
      right: Locations.ROAD,
      bottom: Locations.ROAD,
      left: Locations.ROAD,
    },
    middle: [Locations.TAVERN],
    isSpecial: false,
  },
  {
    id: '003_3',
    edges: {
      top: Locations.FIELD,
      right: Locations.ROAD,
      bottom: Locations.ROAD,
      left: Locations.ROAD,
    },
    middle: [Locations.TAVERN],
    isSpecial: false,
  },
  {
    id: '003_4',
    edges: {
      top: Locations.FIELD,
      right: Locations.ROAD,
      bottom: Locations.ROAD,
      left: Locations.ROAD,
    },
    middle: [Locations.TAVERN],
    isSpecial: false,
  },
  {
    id: '004_1',
    edges: {
      top: Locations.ROAD,
      right: Locations.ROAD,
      bottom: Locations.ROAD,
      left: Locations.ROAD,
    },
    middle: [Locations.TAVERN],
    isSpecial: false,
  },
  {
    id: '005_1',
    edges: {
      top: Locations.CITY,
      right: Locations.ROAD,
      bottom: Locations.FIELD,
      left: Locations.ROAD,
    },
    middle: [Locations.ROAD],
    isSpecial: false,
  },
  {
    id: '005_2',
    edges: {
      top: Locations.CITY,
      right: Locations.ROAD,
      bottom: Locations.FIELD,
      left: Locations.ROAD,
    },
    middle: [Locations.ROAD],
    isSpecial: false,
  },
  {
    id: '005_3',
    edges: {
      top: Locations.CITY,
      right: Locations.ROAD,
      bottom: Locations.FIELD,
      left: Locations.ROAD,
    },
    middle: [Locations.ROAD],
    isSpecial: false,
  },
  {
    id: '005_4',
    edges: {
      top: Locations.CITY,
      right: Locations.ROAD,
      bottom: Locations.FIELD,
      left: Locations.ROAD,
    },
    middle: [Locations.ROAD],
    isSpecial: false,
  },
  {
    id: '006_1',
    edges: {
      top: Locations.CITY,
      right: Locations.FIELD,
      bottom: Locations.ROAD,
      left: Locations.ROAD,
    },
    middle: [Locations.ROAD],
    isSpecial: false,
  },
  {
    id: '006_2',
    edges: {
      top: Locations.CITY,
      right: Locations.FIELD,
      bottom: Locations.ROAD,
      left: Locations.ROAD,
    },
    middle: [Locations.ROAD],
    isSpecial: false,
  },
  {
    id: '006_3',
    edges: {
      top: Locations.CITY,
      right: Locations.FIELD,
      bottom: Locations.ROAD,
      left: Locations.ROAD,
    },
    middle: [Locations.ROAD],
    isSpecial: false,
  },
  {
    id: '007_1',
    edges: {
      top: Locations.CITY,
      right: Locations.ROAD,
      bottom: Locations.ROAD,
      left: Locations.FIELD,
    },
    middle: [Locations.ROAD],
    isSpecial: false,
  },
  {
    id: '007_2',
    edges: {
      top: Locations.CITY,
      right: Locations.ROAD,
      bottom: Locations.ROAD,
      left: Locations.FIELD,
    },
    middle: [Locations.ROAD],
    isSpecial: false,
  },
  {
    id: '007_3',
    edges: {
      top: Locations.CITY,
      right: Locations.ROAD,
      bottom: Locations.ROAD,
      left: Locations.FIELD,
    },
    middle: [Locations.ROAD],
    isSpecial: false,
  },
  {
    id: '008_1',
    edges: {
      top: Locations.CITY,
      right: Locations.ROAD,
      bottom: Locations.ROAD,
      left: Locations.ROAD,
    },
    middle: [Locations.TAVERN],
    isSpecial: false,
  },
  {
    id: '008_2',
    edges: {
      top: Locations.CITY,
      right: Locations.ROAD,
      bottom: Locations.ROAD,
      left: Locations.ROAD,
    },
    middle: [Locations.TAVERN],
    isSpecial: false,
  },
  {
    id: '008_3',
    edges: {
      top: Locations.CITY,
      right: Locations.ROAD,
      bottom: Locations.ROAD,
      left: Locations.ROAD,
    },
    middle: [Locations.TAVERN],
    isSpecial: false,
  },
  {
    id: '009_1',
    edges: {
      top: Locations.CITY,
      right: Locations.FIELD,
      bottom: Locations.FIELD,
      left: Locations.FIELD,
    },
    middle: [Locations.FIELD],
    isSpecial: false,
  },
  {
    id: '009_2',
    edges: {
      top: Locations.CITY,
      right: Locations.FIELD,
      bottom: Locations.FIELD,
      left: Locations.FIELD,
    },
    middle: [Locations.FIELD],
    isSpecial: false,
  },
  {
    id: '009_3',
    edges: {
      top: Locations.CITY,
      right: Locations.FIELD,
      bottom: Locations.FIELD,
      left: Locations.FIELD,
    },
    middle: [Locations.FIELD],
    isSpecial: false,
  },
  {
    id: '009_4',
    edges: {
      top: Locations.CITY,
      right: Locations.FIELD,
      bottom: Locations.FIELD,
      left: Locations.FIELD,
    },
    middle: [Locations.FIELD],
    isSpecial: false,
  },
  {
    id: '009_5',
    edges: {
      top: Locations.CITY,
      right: Locations.FIELD,
      bottom: Locations.FIELD,
      left: Locations.FIELD,
    },
    middle: [Locations.FIELD],
    isSpecial: false,
  },
  {
    id: '010_1',
    edges: {
      top: Locations.CITY,
      right: Locations.CITY,
      bottom: Locations.FIELD,
      left: Locations.CITY,
    },
    middle: [Locations.CITY],
    isSpecial: false,
  },
  {
    id: '011_1',
    edges: {
      top: Locations.CITY,
      right: Locations.CITY,
      bottom: Locations.FIELD,
      left: Locations.CITY,
    },
    middle: [Locations.CITY],
    isSpecial: true,
  },
  {
    id: '011_2',
    edges: {
      top: Locations.CITY,
      right: Locations.CITY,
      bottom: Locations.FIELD,
      left: Locations.CITY,
    },
    middle: [Locations.CITY],
    isSpecial: true,
  },
  {
    id: '012_1',
    edges: {
      top: Locations.CITY,
      right: Locations.CITY,
      bottom: Locations.ROAD,
      left: Locations.CITY,
    },
    middle: [Locations.CITY],
    isSpecial: false,
  },
  {
    id: '012_2',
    edges: {
      top: Locations.CITY,
      right: Locations.CITY,
      bottom: Locations.ROAD,
      left: Locations.CITY,
    },
    middle: [Locations.CITY],
    isSpecial: false,
  },
  {
    id: '012_3',
    edges: {
      top: Locations.CITY,
      right: Locations.CITY,
      bottom: Locations.ROAD,
      left: Locations.CITY,
    },
    middle: [Locations.CITY],
    isSpecial: false,
  },
  {
    id: '013_1',
    edges: {
      top: Locations.CITY,
      right: Locations.CITY,
      bottom: Locations.ROAD,
      left: Locations.CITY,
    },
    middle: [Locations.CITY],
    isSpecial: true,
  },
  {
    id: '014_1',
    edges: {
      top: Locations.CITY,
      right: Locations.CITY,
      bottom: Locations.CITY,
      left: Locations.CITY,
    },
    middle: [Locations.CITY],
    isSpecial: true,
  },
  {
    id: '015_1',
    edges: {
      top: Locations.CITY,
      right: Locations.FIELD,
      bottom: Locations.FIELD,
      left: Locations.CITY,
    },
    middle: [Locations.CITY],
    isSpecial: false,
  },
  {
    id: '015_2',
    edges: {
      top: Locations.CITY,
      right: Locations.FIELD,
      bottom: Locations.FIELD,
      left: Locations.CITY,
    },
    middle: [Locations.CITY],
    isSpecial: false,
  },
  {
    id: '015_3',
    edges: {
      top: Locations.CITY,
      right: Locations.FIELD,
      bottom: Locations.FIELD,
      left: Locations.CITY,
    },
    middle: [Locations.CITY],
    isSpecial: false,
  },
  {
    id: '016_1',
    edges: {
      top: Locations.CITY,
      right: Locations.FIELD,
      bottom: Locations.FIELD,
      left: Locations.CITY,
    },
    middle: [Locations.CITY],
    isSpecial: true,
  },
  {
    id: '016_2',
    edges: {
      top: Locations.CITY,
      right: Locations.FIELD,
      bottom: Locations.FIELD,
      left: Locations.CITY,
    },
    middle: [Locations.CITY],
    isSpecial: true,
  },
  {
    id: '017_1',
    edges: {
      top: Locations.FIELD,
      right: Locations.CITY,
      bottom: Locations.FIELD,
      left: Locations.CITY,
    },
    middle: [Locations.CITY],
    isSpecial: false,
  },
  {
    id: '018_1',
    edges: {
      top: Locations.FIELD,
      right: Locations.CITY,
      bottom: Locations.FIELD,
      left: Locations.CITY,
    },
    middle: [Locations.CITY],
    isSpecial: true,
  },
  {
    id: '018_2',
    edges: {
      top: Locations.FIELD,
      right: Locations.CITY,
      bottom: Locations.FIELD,
      left: Locations.CITY,
    },
    middle: [Locations.CITY],
    isSpecial: true,
  },
  {
    id: '019_1',
    edges: {
      top: Locations.CITY,
      right: Locations.ROAD,
      bottom: Locations.ROAD,
      left: Locations.CITY,
    },
    middle: [Locations.CITY, Locations.ROAD],
    isSpecial: false,
  },
  {
    id: '019_2',
    edges: {
      top: Locations.CITY,
      right: Locations.ROAD,
      bottom: Locations.ROAD,
      left: Locations.CITY,
    },
    middle: [Locations.CITY, Locations.ROAD],
    isSpecial: false,
  },
  {
    id: '019_3',
    edges: {
      top: Locations.CITY,
      right: Locations.ROAD,
      bottom: Locations.ROAD,
      left: Locations.CITY,
    },
    middle: [Locations.CITY, Locations.ROAD],
    isSpecial: false,
  },
  {
    id: '020_1',
    edges: {
      top: Locations.CITY,
      right: Locations.ROAD,
      bottom: Locations.ROAD,
      left: Locations.CITY,
    },
    middle: [Locations.CITY, Locations.ROAD],
    isSpecial: true,
  },
  {
    id: '020_2',
    edges: {
      top: Locations.CITY,
      right: Locations.ROAD,
      bottom: Locations.ROAD,
      left: Locations.CITY,
    },
    middle: [Locations.CITY, Locations.ROAD],
    isSpecial: true,
  },
  {
    id: '021_1',
    edges: {
      top: Locations.FIELD,
      right: Locations.FIELD,
      bottom: Locations.ROAD,
      left: Locations.FIELD,
    },
    middle: [Locations.MONASTERY],
    isSpecial: false,
  },
  {
    id: '021_2',
    edges: {
      top: Locations.FIELD,
      right: Locations.FIELD,
      bottom: Locations.ROAD,
      left: Locations.FIELD,
    },
    middle: [Locations.MONASTERY],
    isSpecial: false,
  },
  {
    id: '022_1',
    edges: {
      top: Locations.FIELD,
      right: Locations.FIELD,
      bottom: Locations.FIELD,
      left: Locations.FIELD,
    },
    middle: [Locations.MONASTERY],
    isSpecial: false,
  },
  {
    id: '022_2',
    edges: {
      top: Locations.FIELD,
      right: Locations.FIELD,
      bottom: Locations.FIELD,
      left: Locations.FIELD,
    },
    middle: [Locations.MONASTERY],
    isSpecial: false,
  },
  {
    id: '022_3',
    edges: {
      top: Locations.FIELD,
      right: Locations.FIELD,
      bottom: Locations.FIELD,
      left: Locations.FIELD,
    },
    middle: [Locations.MONASTERY],
    isSpecial: false,
  },
  {
    id: '022_4',
    edges: {
      top: Locations.FIELD,
      right: Locations.FIELD,
      bottom: Locations.FIELD,
      left: Locations.FIELD,
    },
    middle: [Locations.MONASTERY],
    isSpecial: false,
  },
  {
    id: '023_1',
    edges: {
      top: Locations.CITY,
      right: Locations.FIELD,
      bottom: Locations.CITY,
      left: Locations.FIELD,
    },
    middle: [Locations.FIELD],
    isSpecial: false,
  },
  {
    id: '023_2',
    edges: {
      top: Locations.CITY,
      right: Locations.FIELD,
      bottom: Locations.CITY,
      left: Locations.FIELD,
    },
    middle: [Locations.FIELD],
    isSpecial: false,
  },
  {
    id: '023_3',
    edges: {
      top: Locations.CITY,
      right: Locations.FIELD,
      bottom: Locations.CITY,
      left: Locations.FIELD,
    },
    middle: [Locations.FIELD],
    isSpecial: false,
  },
  {
    id: '024_1',
    edges: {
      top: Locations.CITY,
      right: Locations.FIELD,
      bottom: Locations.FIELD,
      left: Locations.CITY,
    },
    middle: [Locations.FIELD],
    isSpecial: false,
  },
  {
    id: '024_2',
    edges: {
      top: Locations.CITY,
      right: Locations.FIELD,
      bottom: Locations.FIELD,
      left: Locations.CITY,
    },
    middle: [Locations.FIELD],
    isSpecial: false,
  },
];
